-- ============================================================================
-- CANONICAL CURRENT DEFINITION — evetis_mart.V_PROMO_ECONOMICS_SCENARIO_HISTORY (VIEW)
-- Authoritative Git definition. Rules: sql/current/README.md. Metadata: MANIFEST.json.
-- Origin: PR-PROMO-3 (Git-first, pending_deploy). Contract:
-- docs/promotions/PR_PROMO_3_ECONOMICS_INTEGRATION_2026-09-24.md.
-- Нейтральный слой: читает только wb_mart, ozon_mart и evetis_mart. Экономику НЕ считает —
-- она посчитана в представлениях площадок по их каноническим контрактам (WB_FE_V1, Ozon
-- FORWARD_MODELLED). EXPECTED сопоставим между площадками, downside — НЕТ: у WB это
-- стресс p90, у Ozon WORST по максимальной логистике (downside_case на строке).
--
-- Грейн: marketplace × economics_slot × scenario_entity_key
-- (scenario_entity_key = площадка | акция | товар | сценарий).
-- ============================================================================
CREATE OR REPLACE VIEW `project-fa311fc0-4d87-4781-986.evetis_mart.V_PROMO_ECONOMICS_SCENARIO_HISTORY`
OPTIONS (description = "PR-PROMO-3. История сценариев экономики акций обеих площадок по слотам: одна строка на marketplace × economics_slot × scenario_entity_key. BASELINE — канон при текущей цене продавца (не экономика акции), PROMO — по цене источника с явным смыслом и осью применимости. Вклад, маржа, break-even, требуемый рост продаж, downside своей площадки. Экономика только из снимков базиса слота — прошлое не переписывается. Без рекомендаций, запасов и налога.")
AS
SELECT
  marketplace,
  economics_slot,
  CONCAT(marketplace, '|', IFNULL(CAST(promotion_id AS STRING), '-'), '|',
         IFNULL(CAST(nm_id AS STRING), CONCAT('sku:', IFNULL(internal_sku, '-'))), '|', scenario_key) AS scenario_entity_key,
  observation_id,
  observed_at,
  basis_snapshot_id,
  basis_captured_at,
  history_class,
  CAST(promotion_id AS STRING) AS source_promotion_id,
  promotion_type,
  promotion_lifecycle_status,
  promotion_starts_at,
  CAST(nm_id AS STRING) AS marketplace_product_id,
  CAST(NULL AS STRING) AS offer_id,
  internal_sku,
  mapping_status,
  sku_state,
  evidence_source,
  scenario_type,
  scenario_key,
  price_interpretation,
  auto_add_at,
  currency,
  currency_basis,
  scenario_price_rub,
  price_source,
  price_observed_at,
  price_evidence_status,
  price_binding_evidence,
  promotion_link_evidence,
  CAST(NULL AS NUMERIC) AS observed_seller_price_rub,
  baseline_price_rub,
  baseline_price_source,
  baseline_price_observed_at,
  CAST(NULL AS BOOL) AS baseline_includes_promotion_effect,
  cogs_rub,
  cogs_source,
  cogs_effective_from,
  economics_model_version,
  temporal_basis,
  economics_status,
  CAST(baseline_contribution_expected_rub AS NUMERIC) AS baseline_contribution_expected_rub,
  CAST(promo_contribution_expected_rub AS NUMERIC) AS promo_contribution_expected_rub,
  CAST(delta_contribution_expected_rub AS NUMERIC) AS delta_contribution_expected_rub,
  CAST(baseline_margin_expected_pct AS NUMERIC) AS baseline_margin_expected_pct,
  CAST(promo_margin_expected_pct AS NUMERIC) AS promo_margin_expected_pct,
  CAST(break_even_price_expected_rub AS NUMERIC) AS break_even_price_expected_rub,
  CAST(promo_price_minus_break_even_rub AS NUMERIC) AS promo_price_minus_break_even_rub,
  CAST(canonical_contribution_at_baseline_rub AS NUMERIC) AS canonical_contribution_at_baseline_rub,
  downside_case,
  downside_evidence_class,
  CAST(baseline_contribution_downside_rub AS NUMERIC) AS baseline_contribution_downside_rub,
  CAST(promo_contribution_downside_rub AS NUMERIC) AS promo_contribution_downside_rub,
  promo_downside_negative,
  uplift_status,
  CAST(required_sales_uplift_pct AS NUMERIC) AS required_sales_uplift_pct,
  uplift_interpretation
FROM `project-fa311fc0-4d87-4781-986.wb_mart.V_WB_PROMO_ECONOMICS_SCENARIO_HISTORY`
UNION ALL
SELECT
  marketplace,
  economics_slot,
  CONCAT(marketplace, '|', IFNULL(CAST(action_id AS STRING), '-'), '|',
         IFNULL(CAST(product_id AS STRING), CONCAT('sku:', IFNULL(internal_sku, '-'))), '|', scenario_key),
  observation_id,
  observed_at,
  basis_snapshot_id,
  basis_captured_at,
  history_class,
  CAST(action_id AS STRING),
  promotion_type,
  promotion_lifecycle_status,
  promotion_starts_at,
  CAST(product_id AS STRING),
  offer_id,
  internal_sku,
  mapping_status,
  sku_state,
  evidence_source,
  scenario_type,
  scenario_key,
  price_interpretation,
  auto_add_at,
  currency,
  currency_basis,
  scenario_price_rub,
  price_source,
  price_observed_at,
  price_evidence_status,
  price_binding_evidence,
  promotion_link_evidence,
  observed_seller_price_rub,
  baseline_price_rub,
  baseline_price_source,
  baseline_price_observed_at,
  baseline_includes_promotion_effect,
  cogs_rub,
  cogs_source,
  cogs_effective_from,
  economics_model_version,
  temporal_basis,
  economics_status,
  baseline_contribution_expected_rub,
  promo_contribution_expected_rub,
  delta_contribution_expected_rub,
  baseline_margin_expected_pct,
  promo_margin_expected_pct,
  break_even_price_expected_rub,
  promo_price_minus_break_even_rub,
  canonical_contribution_at_baseline_rub,
  downside_case,
  downside_evidence_class,
  baseline_contribution_downside_rub,
  promo_contribution_downside_rub,
  promo_downside_negative,
  uplift_status,
  required_sales_uplift_pct,
  uplift_interpretation
FROM `project-fa311fc0-4d87-4781-986.ozon_mart.V_OZON_PROMO_ECONOMICS_SCENARIO_HISTORY`
